{
 "title": "CRDB",
 "tags": [ "RLEC" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster1", "query": "label_values(node_up,cluster)" },
   {
    "name": "bdb1",
    "label": "BDB1",
    "query": "label_values(bdb_conns{cluster=\"$cluster1\"}, bdb)"
   },
   { "name": "cluster2", "query": "label_values(node_up,cluster)" },
   {
    "name": "bdb2",
    "label": "BDB2",
    "query": "label_values(bdb_conns{cluster=\"$cluster2\"}, bdb)"
   },
   { "name": "cluster3", "query": "label_values(node_up,cluster)" },
   {
    "name": "bdb3",
    "label": "BDB3",
    "query": "label_values(bdb_conns{cluster=\"$cluster2\"}, bdb)"
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bdb_avg_latency{bdb=\"$bdb1\", cluster=\"$cluster1\"}",
     "legendFormat": "bdb1 bdb_avg_latency"
    },
    {
     "expr": "bdb_avg_write_latency{bdb=\"$bdb1\", cluster=\"$cluster1\"}",
     "legendFormat": "bdb1 bdb_avg_write_latency"
    },
    {
     "expr": "bdb_avg_read_latency{bdb=\"$bdb1\", cluster=\"$cluster1\"}",
     "legendFormat": "bdb1 bdb_avg_read_latency"
    },
    {
     "expr": "bdb_avg_other_latency{bdb=\"$bdb1\", cluster=\"$cluster1\"}",
     "legendFormat": "bdb1 bdb_avg_other_latency"
    },
    {
     "expr": "max_over_time(bdb_avg_latency_max{bdb=\"$bdb1\", cluster=\"$cluster1\"}[$aggregation])",
     "legendFormat": "bdb1 bdb_avg_latency (max over $aggregation)"
    },
    {
     "expr": "bdb_avg_latency{bdb=\"$bdb2\", cluster=\"$cluster2\"}",
     "legendFormat": "bdb2 bdb_avg_latency"
    },
    {
     "expr": "bdb_avg_write_latency{bdb=\"$bdb2\", cluster=\"$cluster2\"}",
     "legendFormat": "bdb2 bdb_avg_write_latency"
    },
    {
     "expr": "bdb_avg_read_latency{bdb=\"$bdb2\", cluster=\"$cluster2\"}",
     "legendFormat": "bdb2 bdb_avg_read_latency"
    },
    {
     "expr": "bdb_avg_other_latency{bdb=\"$bdb2\", cluster=\"$cluster2\"}",
     "legendFormat": "bdb2 bdb_avg_other_latency"
    },
    {
     "expr": "max_over_time(bdb_avg_latency_max{bdb=\"$bdb2\", cluster=\"$cluster2\"}[$aggregation])",
     "legendFormat": "bdb2 bdb_avg_latency (max over $aggregation)"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bdb_used_memory{bdb=\"$bdb1\", cluster=\"$cluster1\"}",
     "legendFormat": "bdb1 used_memory"
    },
    {
     "expr": "bdb_used_memory{bdb=\"$bdb2\", cluster=\"$cluster2\"}",
     "legendFormat": "bdb2 used_memory"
    },
    {
     "expr": "bdb_used_memory{bdb=\"$bdb3\", cluster=\"$cluster3\"}",
     "legendFormat": "bdb3 used_memory"
    },
    {
     "expr": "bdb_memory_limit{bdb=\"$bdb1\", cluster=\"$cluster1\"} < bdb_used_memory{bdb=\"$bdb1\", cluster=\"$cluster1\"} * 1.5",
     "legendFormat": "bdb1 memory_limit (when low)"
    },
    {
     "expr": "bdb_memory_limit{bdb=\"$bdb2\", cluster=\"$cluster2\"} < bdb_used_memory{bdb=\"$bdb2\", cluster=\"$cluster2\"} * 1.5",
     "legendFormat": "bdb2 memory_limit (when low)"
    },
    {
     "expr": "bdb_memory_limit{bdb=\"$bdb3\", cluster=\"$cluster3\"} < bdb_used_memory{bdb=\"$bdb3\", cluster=\"$cluster3\"} * 1.5",
     "legendFormat": "bdb3 memory_limit (when low)"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bdb_conns{bdb=\"$bdb1\", cluster=\"$cluster1\"}",
     "legendFormat": "bdb1 Total"
    },
    {
     "expr": "min(listener_conns{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 min endpoint"
    },
    {
     "expr": "max(listener_conns{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 max endpoint"
    },
    {
     "expr": "bdb_conns{bdb=\"$bdb2\", cluster=\"$cluster2\"}",
     "legendFormat": "bdb2 Total"
    },
    {
     "expr": "min(listener_conns{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 min endpoint"
    },
    {
     "expr": "max(listener_conns{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 max endpoint"
    }
   ]
  },
  {
   "title": "CPU usage by shards",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(1,(delta(redis_process_cpu_system_seconds_total{bdb=\"$bdb1\",cluster=\"$cluster1\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$bdb1\",cluster=\"$cluster1\"}[60s]))/60*100 or redis_cpu_percent{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1, top shard: {{redis}} role: {{role}} node:{{node}}"
    },
    {
     "expr": "avg((delta(redis_process_cpu_system_seconds_total{bdb=\"$bdb1\",cluster=\"$cluster1\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$bdb1\",cluster=\"$cluster1\"}[60s]))/60*100 or redis_cpu_percent{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 average"
    },
    {
     "expr": "topk(1,(delta(redis_process_cpu_system_seconds_total{bdb=\"$bdb2\",cluster=\"$cluster2\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$bdb2\",cluster=\"$cluster2\"}[60s]))/60*100 or redis_cpu_percent{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2, top shard: {{redis}} role: {{role}} node:{{node}}"
    },
    {
     "expr": "avg((delta(redis_process_cpu_system_seconds_total{bdb=\"$bdb2\",cluster=\"$cluster2\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$bdb2\",cluster=\"$cluster2\"}[60s]))/60*100 or redis_cpu_percent{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 average"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "# keys/shard",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1,redis_no_of_keys{bdb=\"$bdb1\", cluster=\"$cluster1\"} or redis_db0_keys{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 top redis #{{redis}}"
    },
    {
     "expr": "topk(1,redis_no_of_keys{bdb=\"$bdb2\", cluster=\"$cluster2\"} or redis_db0_keys{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb 2 top redis #{{redis}}"
    },
    {
     "expr": "avg(redis_no_of_keys{bdb=\"$bdb1\", cluster=\"$cluster1\"} or redis_db0_keys{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 avg"
    },
    {
     "expr": "avg(redis_no_of_keys{bdb=\"$bdb2\", cluster=\"$cluster2\"} or redis_db0_keys{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 avg"
    }
   ]
  },
  {
   "title": "#Keys for BDB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_no_of_keys{bdb=\"$bdb1\", cluster=\"$cluster1\"}",
     "legendFormat": "bdb1: num of keys"
    },
    {
     "expr": "sum(redis_db0_expires{bdb=\"$bdb1\", cluster=\"$cluster1\",role=\"master\"})",
     "legendFormat": "bdb1: num of volatile keys"
    },
    {
     "expr": "sum(redis_bigdb0_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "ram keys"
    },
    {
     "expr": "sum(redis_bigdb0_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "disk keys"
    },
    {
     "expr": "(sum(redis_bigdb0_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) + sum(redis_bigdb0_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})) - sum(redis_bigdb0_keys{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "overlapping keys"
    },
    {
     "expr": "sum(redis_bigdb0_dirty{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "dirty keys"
    },
    {
     "expr": "sum(redis_bigdb0_clean{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "clean keys"
    },
    {
     "expr": "bdb_no_of_keys{bdb=\"$bdb2\", cluster=\"$cluster2\"}",
     "legendFormat": "bdb2: num of keys"
    },
    {
     "expr": "sum(redis_db0_expires{bdb=\"$bdb2\", cluster=\"$cluster2\",role=\"master\"})",
     "legendFormat": "bdb2: num of volatile keys"
    }
   ]
  },
  {
   "title": "Expired objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(delta(redis_expired_keys{bdb=\"$bdb1\", cluster=\"$cluster1\"}[1m]))",
     "legendFormat": "bdb1"
    },
    {
     "expr": "sum(delta(redis_expired_keys{bdb=\"$bdb2\", cluster=\"$cluster2\"}[1m]))",
     "legendFormat": "bdb2"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Requests[total,read,write,other]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_total_req{cluster=\"$cluster1\",bdb=\"$bdb1\"}",
     "legendFormat": "bdb1 total requests"
    },
    {
     "expr": "bdb_other_req{cluster=\"$cluster1\",bdb=\"$bdb1\"}",
     "legendFormat": "bdb1 other requests"
    },
    {
     "expr": "bdb_read_req{cluster=\"$cluster1\",bdb=\"$bdb1\"}",
     "legendFormat": "bdb1 read requests"
    },
    {
     "expr": "bdb_write_req{cluster=\"$cluster1\",bdb=\"$bdb1\"}",
     "legendFormat": "bdb1 write requests"
    },
    {
     "expr": "bdb_total_req_max{cluster=\"$cluster1\",bdb=\"$bdb1\"}",
     "legendFormat": "bdb1 total requests (max)"
    },
    {
     "expr": "max_over_time(bdb_total_req{cluster=\"$cluster1\",bdb=\"$bdb1\"}[$aggregation])\n",
     "legendFormat": "bdb1 bdb_total_req(max over $aggregation)"
    },
    {
     "expr": "bdb_total_req{cluster=\"$cluster2\",bdb=\"$bdb2\"}",
     "legendFormat": "bdb2 total requests"
    },
    {
     "expr": "bdb_other_req{cluster=\"$cluster2\",bdb=\"$bdb2\"}",
     "legendFormat": "bdb2 other requests"
    },
    {
     "expr": "bdb_read_req{cluster=\"$cluster2\",bdb=\"$bdb2\"}",
     "legendFormat": "bdb2 read requests"
    },
    {
     "expr": "bdb_write_req{cluster=\"$cluster2\",bdb=\"$bdb2\"}",
     "legendFormat": "bdb2 write requests"
    },
    {
     "expr": "bdb_total_req_max{cluster=\"$cluster2\",bdb=\"$bdb2\"}",
     "legendFormat": "bdb2 total requests (max)"
    },
    {
     "expr": "max_over_time(bdb_total_req{cluster=\"$cluster2\",bdb=\"$bdb2\"}[$aggregation])\n",
     "legendFormat": "bdb2 bdb_total_req(max over $aggregation)"
    }
   ]
  },
  {
   "title": "Ingress/Egress",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "Bps", "label": "Ingress" }
   ],
   "targets": [
    {
     "expr": "bdb_egress_bytes{bdb=\"$bdb1\",cluster=\"$cluster1\"}",
     "legendFormat": "bdb 1 Egress"
    },
    {
     "expr": "bdb_ingress_bytes{bdb=\"$bdb1\",cluster=\"$cluster1\"}",
     "legendFormat": "bdb 1 Ingress"
    },
    {
     "expr": "bdb_egress_bytes{bdb=\"$bdb2\",cluster=\"$cluster2\"}",
     "legendFormat": "bdb 2 Egress"
    },
    {
     "expr": "bdb_ingress_bytes{bdb=\"$bdb2\",cluster=\"$cluster2\"}",
     "legendFormat": "bdb 2 Ingress"
    }
   ]
  },
  {
   "title": "Sizes of shards",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(2,redis_used_memory{bdb=\"$bdb1\",cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 top redis:{{redis}}, bdb:{{bdb}},  role:{{role}}, Slots: {{slots}}"
    },
    {
     "expr": "avg(redis_used_memory{bdb=\"$bdb1\",cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 avg"
    },
    {
     "expr": "topk(2,redis_used_memory{bdb=\"$bdb2\",cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 top redis:{{redis}}, bdb:{{bdb}},  role:{{role}}, Slots: {{slots}}"
    },
    {
     "expr": "avg(redis_used_memory{bdb=\"$bdb2\",cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 avg"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Shard AOF Rewrites / $aggregation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(redis_aof_rewrites{cluster=\"$cluster1\", bdb=\"$bdb1\"}[$aggregation]) !=0",
     "legendFormat": "bdb1 Redis {{redis}} node {{node}}"
    },
    {
     "expr": "delta(redis_aof_rewrites{cluster=\"$cluster2\", bdb=\"$bdb2\"}[$aggregation]) !=0",
     "legendFormat": "bdb2 Redis {{redis}} node {{node}}"
    }
   ]
  },
  {
   "title": "forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_bgsave_in_progress{cluster=\"$cluster1\", bdb=\"$bdb1\"} !=0",
     "legendFormat": "bdb 1 BGSAVE {{redis}} node {{node}}"
    },
    {
     "expr": "redis_aof_rewrite_in_progress{cluster=\"$cluster1\", bdb=\"$bdb1\"} !=0",
     "legendFormat": "bdb 1 AOFRW {{redis}} node {{node}}"
    },
    {
     "expr": "redis_rdb_bgsave_in_progress{cluster=\"$cluster2\", bdb=\"$bdb2\"} !=0",
     "legendFormat": "bdb 2 BGSAVE {{redis}} node {{node}}"
    },
    {
     "expr": "redis_aof_rewrite_in_progress{cluster=\"$cluster2\", bdb=\"$bdb2\"} !=0",
     "legendFormat": "bdb 2 AOFRW {{redis}} node {{node}}"
    }
   ]
  },
  {
   "title": "Read/Write Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "bdb_read_misses{cluster=\"$cluster1\", bdb=\"$bdb1\"}",
     "legendFormat": "bdb1 Read Misses"
    },
    {
     "expr": "bdb_write_misses{cluster=\"$cluster1\", bdb=\"$bdb1\"}",
     "legendFormat": "bdb1 Write Misses"
    },
    {
     "expr": "bdb_read_misses{cluster=\"$cluster2\", bdb=\"$bdb2\"}",
     "legendFormat": "bdb2 Read Misses"
    },
    {
     "expr": "bdb_write_misses{cluster=\"$cluster2\", bdb=\"$bdb2\"}",
     "legendFormat": "bdb2 Write Misses"
    },
    {
     "expr": "bdb_read_hits{cluster=\"$cluster1\", bdb=\"$bdb1\"}",
     "legendFormat": "bdb1 Read HIts"
    },
    {
     "expr": "bdb_write_hits{cluster=\"$cluster1\", bdb=\"$bdb1\"}",
     "legendFormat": "bdb1 Write Hits"
    },
    {
     "expr": "bdb_read_hits{cluster=\"$cluster2\", bdb=\"$bdb2\"}",
     "legendFormat": "bdb2 Read HIts"
    },
    {
     "expr": "bdb_write_hits{cluster=\"$cluster2\", bdb=\"$bdb2\"}",
     "legendFormat": "bdb2 Write Hits"
    }
   ]
  },
  {
   "title": "DB Hit Ratio (hits / requests)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(bdb_read_hits{bdb=\"$bdb1\", cluster=\"$cluster1\"} + bdb_write_hits{bdb=\"$bdb1\", cluster=\"$cluster1\"}) / (bdb_read_req{bdb=\"$bdb1\", cluster=\"$cluster1\"} + bdb_write_req{bdb=\"$bdb1\", cluster=\"$cluster1\"}) > 0",
     "legendFormat": "bdb 1 hit ratio"
    },
    {
     "expr": "(bdb_read_hits{bdb=\"$bdb2\", cluster=\"$cluster2\"} + bdb_write_hits{bdb=\"$bdb2\", cluster=\"$cluster2\"}) / (bdb_read_req{bdb=\"$bdb2\", cluster=\"$cluster2\"} + bdb_write_req{bdb=\"$bdb2\", cluster=\"$cluster2\"}) > 0",
     "legendFormat": "bdb 2 hit ratio"
    }
   ]
  },
  {
   "title": "Delayed fsync - (events / $aggregation)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(redis_aof_delayed_fsync{bdb=\"$bdb1\", cluster=\"$cluster1\"}[$aggregation]))",
     "legendFormat": "bdb1"
    },
    {
     "expr": "sum(delta(redis_aof_delayed_fsync{bdb=\"$bdb2\", cluster=\"$cluster2\"}[$aggregation]))",
     "legendFormat": "bdb2"
    }
   ]
  },
  {
   "title": "bdb_crdt_syncer_status: [ in-sync: 0,   syncing: 1,   out-of-sync: 2 ]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "none", "label": "state" }
   ],
   "targets": [
    {
     "expr": "bdb_crdt_syncer_status{bdb=\"$bdb1\", cluster=\"$cluster1\"}",
     "legendFormat": "bdb1"
    },
    {
     "expr": "bdb_crdt_syncer_status{bdb=\"$bdb2\", cluster=\"$cluster2\"}",
     "legendFormat": "bdb2"
    }
   ]
  },
  {
   "title": "redis_crdt_peer_peer_state != 1.  [ initialized: 0, online: 1, wait_fullsync: 2, fullsync: 3, fullsync_ack: 4, closed: 5 ]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none", "label": "status" }
   ],
   "targets": [
    {
     "expr": "redis_crdt_peer_peer_state{bdb=\"$bdb1\", cluster=\"$cluster1\"} != 1",
     "legendFormat": "bdb1 redis:{{redis}}"
    },
    {
     "expr": "redis_crdt_peer_peer_state{bdb=\"$bdb2\", cluster=\"$cluster2\"} != 1",
     "legendFormat": "bdb2 redis:{{redis}}"
    }
   ]
  },
  {
   "title": "redis_crdt_stale_replica , redis_crdt_oom_latch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_crdt_stale_replica{bdb=\"$bdb1\", cluster=\"$cluster1\"} > 0",
     "legendFormat": "stale - bdb1 redis:{{redis}}"
    },
    {
     "expr": "redis_crdt_stale_replica{bdb=\"$bdb2\", cluster=\"$cluster2\"} > 0",
     "legendFormat": "stale - bdb2 redis:{{redis}}"
    },
    {
     "expr": "redis_crdt_oom_latch{bdb=\"$bdb1\", cluster=\"$cluster1\"} > 0",
     "legendFormat": "oom - bdb1 redis:{{redis}}"
    },
    {
     "expr": "redis_crdt_oom_latch{bdb=\"$bdb2\", cluster=\"$cluster2\"} > 0",
     "legendFormat": "oom - bdb2 redis:{{redis}}"
    }
   ]
  },
  { "title": "Syncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "replica min/max ops lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "min(redis_crdt_replica_min_ops_lag{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 min lag"
    },
    {
     "expr": "min(redis_crdt_replica_min_ops_lag{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 min lag"
    },
    {
     "expr": "max(redis_crdt_replica_max_ops_lag{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 max lag"
    },
    {
     "expr": "max(redis_crdt_replica_max_ops_lag{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 max lag"
    }
   ]
  },
  {
   "title": "GC ops lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(bdb_crdt_syncer_pending_local_writes_max{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 max local writes"
    },
    {
     "expr": "max(bdb_crdt_syncer_pending_local_writes_max{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 max local writes"
    },
    {
     "expr": "min(bdb_crdt_syncer_pending_local_writes_min{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 min local writes"
    },
    {
     "expr": "min(bdb_crdt_syncer_pending_local_writes_min{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 min local writes"
    }
   ]
  },
  {
   "title": "crdt_syncer_local_ingress_lag_time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "bdb_crdt_syncer_local_ingress_lag_time{bdb=\"$bdb1\", cluster=\"$cluster1\"}",
     "legendFormat": "bdb1 syncer_local_ingress_lag_time"
    },
    {
     "expr": "bdb_crdt_syncer_local_ingress_lag_time{bdb=\"$bdb2\", cluster=\"$cluster2\"}",
     "legendFormat": "bdb2 syncer_local_ingress_lag_time"
    }
   ]
  },
  { "title": "crdt module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "CRDT GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(delta(redis_crdt_gc_attempted{bdb=\"$bdb1\", cluster=\"$cluster1\"}[1m]))",
     "legendFormat": "bdb1 crdt_gc_attempted"
    },
    {
     "expr": "sum(delta(redis_crdt_gc_attempted{bdb=\"$bdb2\", cluster=\"$cluster2\"}[1m]))",
     "legendFormat": "bdb2 crdt_gc_attempted"
    },
    {
     "expr": "sum(delta(redis_crdt_gc_collected{bdb=\"$bdb1\", cluster=\"$cluster1\"}[1m]))",
     "legendFormat": "bdb1 crdt_gc_collected"
    },
    {
     "expr": "sum(delta(redis_crdt_gc_collected{bdb=\"$bdb2\", cluster=\"$cluster2\"}[1m]))",
     "legendFormat": "bdb2 crdt_gc_collected"
    },
    {
     "expr": "sum(redis_crdt_gc_pending{bdb=\"$bdb1\", cluster=\"$cluster1\"})",
     "legendFormat": "bdb1 gc pending"
    },
    {
     "expr": "sum(redis_crdt_gc_pending{bdb=\"$bdb2\", cluster=\"$cluster2\"})",
     "legendFormat": "bdb2 gc pending"
    }
   ]
  },
  {
   "title": "ROF Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB ram hit ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) > 0",
       "legendFormat": "DB ram hit ratio"
      },
      {
       "expr": "bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "read hit ratio"
      },
      {
       "expr": "bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "write hit ratio"
      },
      {
       "expr": "bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "del hit ratio"
      }
     ]
    },
    {
     "title": "Flash IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_io_reads{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_writes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      },
      {
       "expr": "bdb_bigstore_io_dels{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "Flash IO Banwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_io_read_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_write_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "graph",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\"}[1m])/60",
       "legendFormat": "RAM Ops for Redis {{redis}}"
      },
      {
       "expr": "delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\"}[1m]) / -60",
       "legendFormat": "Flash Ops for Redis {{redis}}"
      }
     ]
    },
    {
     "title": "BDB RAM:Flash access ratio",
     "type": "graph",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg(delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "Flash Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "User RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "User Flash Ops for Redis"
      }
     ]
    },
    {
     "title": "BDB sum redis wait busy key / $aggregation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_wait_busy_key{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB (ROF) used RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 8, "y": 93 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bdb_used_ram{bdb=\"$bdb1\", cluster=\"$cluster1\"}"
      },
      {
       "expr": "bdb_ram_limit{bdb=\"$bdb1\", cluster=\"$cluster1\"} < bdb_used_ram{bdb=\"$bdb1\", cluster=\"$cluster1\"} * 1.5"
      }
     ]
    },
    {
     "title": "BDB used flash",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "used"
      },
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"} * bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "actual"
      },
      {
       "expr": "bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "frag ratio"
      }
     ]
    },
    {
     "title": "BDB postponed clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_postponed_clients{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB blocked clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_blocked_clients{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "Number of blocked clients"
      }
     ]
    },
    {
     "title": "BDB ram overhead",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bdb_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"}  / bdb_ram_limit{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "Total Ratio"
      },
      {
       "expr": "redis_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"} / redis_max_ram{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "redis: {{redis}} role:{{role}}"
      }
     ]
    },
    {
     "title": "BDB sum redis active defrag running",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "redis_active_defrag_running{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "redis:{{redis}} role:{{role}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_blocking_writes{bdb=\"$bdb\",cluster=\"$cluster\"}[1m]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking reads / $aggregation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_blocking_reads{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "Shard allocator fragmentation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 125 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"} / redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "redis:{{redis}} role:{{role}}"
      }
     ]
    },
    {
     "title": "BDB:$bdb total fragmentation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 133 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(redis_mem_fragmentation_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}) / count(redis_mem_fragmentation_ratio{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "redis_mem_fragmentation_ratio"
      },
      {
       "expr": "sum(redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"}) / sum(redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "Shard allocator fragmentation"
      },
      {
       "expr": "sum(redis_allocator_resident{bdb=\"$bdb\",cluster=\"$cluster\"}) / sum(redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "shard allocator rss"
      }
     ]
    },
    {
     "title": "Shard RSS fragmentation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 133 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "redis_fragmentation{bdb=\"$bdb\", cluster=\"$cluster\"} or redis_mem_fragmentation_ratio{bdb=\"$bdb\", cluster=\"$cluster\"} ",
       "legendFormat": "Redis {{redis}} ({{role}})"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg read io queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_read_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg write io queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_write_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB objects(values) in FLASH",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_objs_flash{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in flash (sum of all master shards)"
      },
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in ram (sum of all master shards)"
      }
     ]
    },
    {
     "title": "BDB % values in RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 149 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"} / bdb_no_of_keys{bdb=\"$bdb\",cluster=\"$cluster\"} ",
       "legendFormat": "BDB % values in RAM (masters)"
      },
      {
       "expr": "avg(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} / redis_bigdb0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "average master shard % values in RAM"
      },
      {
       "expr": "avg(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} / redis_bigdb0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"})",
       "legendFormat": "average slave shard % values in RAM"
      },
      {
       "expr": "topk(1, min(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} / redis_bigdb0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest master shard % values in RAM - redsi:{{redis}}"
      },
      {
       "expr": "topk(1, min(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} / redis_bigdb0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest slave shard % values in RAM - redsi:{{redis}}"
      }
     ]
    },
    {
     "title": "Shard objects(values) in RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"})",
       "legendFormat": "average number of values in ram per slave shard"
      },
      {
       "expr": "avg(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "average number of values in ram per master shard"
      },
      {
       "expr": "topk(1, min(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} < redis_bigdb0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per slave shard - redis:{{redis}}"
      },
      {
       "expr": "topk(1, min(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} < redis_bigdb0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per master shard  - redis:{{redis}}"
      }
     ]
    },
    {
     "title": "BDB dirty RAM evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_ram_dirty_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB clean RAM evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_ram_clean_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB main thread CPU utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bdb_main_thread_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_main_thread_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "main threads"
      },
      {
       "expr": "bdb_shard_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_shard_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "all threads"
      },
      {
       "expr": "bdb_fork_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_fork_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "all forks"
      },
      {
       "expr": "bdb_main_thread_cpu_system_max{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_main_thread_cpu_user_max{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "main threads (max)"
      },
      {
       "expr": "bdb_shard_cpu_system_max{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_shard_cpu_user_max{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "all threads (max)"
      }
     ]
    },
    {
     "title": "RocksDB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_rocks_comp_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "compactions"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "flushes"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_slowdown{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "slowdowns / $aggregation"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_stop{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "stalls / $aggregation"
      }
     ]
    }
   ]
  }
 ]
}